# Generated by Django 5.1 on 2024-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Eid', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
            ],
        ),
    ]
