# Generated by Django 5.1 on 2024-09-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Ename',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Eid',
            new_name='eid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
