# Generated by Django 5.1 on 2024-09-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudopapp', '0002_rename_ename_employee_name_rename_eid_employee_eid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='Eid',
        ),
    ]
